add Quantizable Transformers
HuangOwen/Awesome-LLM-Compression pull request #10
Opened 2023-11-16 07:10 UTC by zhimin-z

2023-11-16 07:38 UTC, HuangOwen requested changes
Thanks for the commits, some suggestions before merging:
1. Please put this paper in the correct position (publication/arxiv sequence in time)
2. Please use the arxiv page, not the pdf page as the link to [Paper]
3. This paper has a code repo (https://github.com/Qualcomm-AI-research/outlier-free-transformers) although it's empty, we can add this repo as [Code]

2023-11-16 14:58 UTC, zhimin-z commented
> Thanks for the commits, some suggestions before merging:
> 
> 1. Please put this paper in the correct position (publication/arxiv sequence in time)
> 2. Please use the arxiv page, not the pdf page as the link to [Paper]
> 3. This paper has a code repo (https://github.com/Qualcomm-AI-research/outlier-free-transformers) although it's empty, we can add this repo as [Code]

![image](https://github.com/horseee/Awesome-Efficient-LLM/assets/8592144/84fb55ef-f844-4fe9-bf89-5bd017e1528d)

2023-11-17 02:47 UTC, HuangOwen requested changes
Again, please put this paper in the correct position (publication/arxiv sequence in time). Do not always put a paper at the beginning of a section. In this case, this NeurIPS 2023 paper should appear before all EMNLP papers and the NeurIPS workshop papers.

More concretely, this paper should appear before "Efficient LLM Inference on CPUs" and after "Dissecting the Runtime Performance of the Training, Fine-tuning, and Inference of Large Language Models", which is the correct order of their publication date.

2023-11-17 02:47 UTC, HuangOwen commented on README.md
Again, please put this paper in the correct position (publication/arxiv sequence in time). Do not always put a paper at the beginning of a section. In this case, this NeurIPS 2023 paper should appear before all EMNLP papers and the NeurIPS workshop papers. 

More concretely, this paper should appear before "Efficient LLM Inference on CPUs" and after "Dissecting the Runtime Performance of the Training, Fine-tuning, and Inference of Large Language Models", which is the correct order of their publication date.

2023-11-17 02:59 UTC, HuangOwen approved these changes

2023-11-17 02:59 UTC, merged